# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from supr_send_python_sdk.pydantic.event_trigger_event_requestuser_operations_itemunset import EventTriggerEventRequestuserOperationsItemunset

class EventTriggerEventRequestuserOperationsItem(BaseModel):
    # Use this to add communication channels in user profile. Following channel keys: `$email`, `$sms`, `$whatsapp`, `$androidpush`, `$iospush`, `$slack`, `$webpush`, `$ms_teams`. Add channel as {\"$email\":\"user@example.com\"}
    $append_: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='$append')

    # Use this to remove communication channels from user profile. Following channel keys: `$email`, `$sms`, `$whatsapp`, `$androidpush`, `$iospush`, `$slack`, `$webpush`, `$ms_teams`. Define channel as {\"$email\":\"user@example.com\"}
    $remove_: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='$remove')

    # Use this to set user properties like location, preferred language etc. You can define properties in key-value pair as `{\"$preferred_language\":\"hi\"}`
    $set_: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='$set')

    $unset_: typing.Optional[EventTriggerEventRequestuserOperationsItemunset] = Field(None, alias='$unset')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
