# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from supr_send_python_sdk.pydantic.template_get_content_channel_response_channel import TemplateGetContentChannelResponseChannel
from supr_send_python_sdk.pydantic.template_get_content_channel_response_disabled_languages import TemplateGetContentChannelResponseDisabledLanguages
from supr_send_python_sdk.pydantic.template_get_content_channel_response_versions import TemplateGetContentChannelResponseVersions

class TemplateGetContentChannelResponse(BaseModel):
    id: typing.Optional[int] = Field(None, alias='id')

    channel: typing.Optional[TemplateGetContentChannelResponseChannel] = Field(None, alias='channel')

    is_active: typing.Optional[bool] = Field(None, alias='is_active')

    is_enabled: typing.Optional[bool] = Field(None, alias='is_enabled')

    created_at: typing.Optional[str] = Field(None, alias='created_at')

    updated_at: typing.Optional[str] = Field(None, alias='updated_at')

    disabled_languages: typing.Optional[TemplateGetContentChannelResponseDisabledLanguages] = Field(None, alias='disabled_languages')

    versions: typing.Optional[TemplateGetContentChannelResponseVersions] = Field(None, alias='versions')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
