# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class WorkflowConfigureTriggerRequestUsersItemiospushItem(BaseModel):
    # iOSpush token
    token: str = Field(alias='token')

    # vendor delivering the push notification
    provider: str = Field(alias='provider')

    # unique identifier of user's device. This is used to avoid sending duplicate push notification on the same device
    device_id: typing.Optional[str] = Field(None, alias='device_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
