# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

import unittest

import supr_send_python_sdk
from supr_send_python_sdk.model.brand_update_default_preference_request import BrandUpdateDefaultPreferenceRequest
from supr_send_python_sdk import configuration


class TestBrandUpdateDefaultPreferenceRequest(unittest.TestCase):
    """BrandUpdateDefaultPreferenceRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
