# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from supr_send_python_sdk import schemas  # noqa: F401


class BrandCreateOrUpdateRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "brand_name",
        }
        
        class properties:
            brand_name = schemas.StrSchema
            logo = schemas.StrSchema
            primary_color = schemas.StrSchema
            secondary_color = schemas.StrSchema
            tertiary_color = schemas.StrSchema
            preference_page_url = schemas.StrSchema
        
            @staticmethod
            def social_links() -> typing.Type['BrandCreateOrUpdateRequestSocialLinks']:
                return BrandCreateOrUpdateRequestSocialLinks
            properties = schemas.StrSchema
            __annotations__ = {
                "brand_name": brand_name,
                "logo": logo,
                "primary_color": primary_color,
                "secondary_color": secondary_color,
                "tertiary_color": tertiary_color,
                "preference_page_url": preference_page_url,
                "social_links": social_links,
                "properties": properties,
            }
    
    brand_name: MetaOapg.properties.brand_name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["brand_name"]) -> MetaOapg.properties.brand_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["logo"]) -> MetaOapg.properties.logo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["primary_color"]) -> MetaOapg.properties.primary_color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secondary_color"]) -> MetaOapg.properties.secondary_color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tertiary_color"]) -> MetaOapg.properties.tertiary_color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["preference_page_url"]) -> MetaOapg.properties.preference_page_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["social_links"]) -> 'BrandCreateOrUpdateRequestSocialLinks': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["properties"]) -> MetaOapg.properties.properties: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["brand_name", "logo", "primary_color", "secondary_color", "tertiary_color", "preference_page_url", "social_links", "properties", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["brand_name"]) -> MetaOapg.properties.brand_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["logo"]) -> typing.Union[MetaOapg.properties.logo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["primary_color"]) -> typing.Union[MetaOapg.properties.primary_color, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secondary_color"]) -> typing.Union[MetaOapg.properties.secondary_color, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tertiary_color"]) -> typing.Union[MetaOapg.properties.tertiary_color, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["preference_page_url"]) -> typing.Union[MetaOapg.properties.preference_page_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["social_links"]) -> typing.Union['BrandCreateOrUpdateRequestSocialLinks', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["properties"]) -> typing.Union[MetaOapg.properties.properties, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["brand_name", "logo", "primary_color", "secondary_color", "tertiary_color", "preference_page_url", "social_links", "properties", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        brand_name: typing.Union[MetaOapg.properties.brand_name, str, ],
        logo: typing.Union[MetaOapg.properties.logo, str, schemas.Unset] = schemas.unset,
        primary_color: typing.Union[MetaOapg.properties.primary_color, str, schemas.Unset] = schemas.unset,
        secondary_color: typing.Union[MetaOapg.properties.secondary_color, str, schemas.Unset] = schemas.unset,
        tertiary_color: typing.Union[MetaOapg.properties.tertiary_color, str, schemas.Unset] = schemas.unset,
        preference_page_url: typing.Union[MetaOapg.properties.preference_page_url, str, schemas.Unset] = schemas.unset,
        social_links: typing.Union['BrandCreateOrUpdateRequestSocialLinks', schemas.Unset] = schemas.unset,
        properties: typing.Union[MetaOapg.properties.properties, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BrandCreateOrUpdateRequest':
        return super().__new__(
            cls,
            *args,
            brand_name=brand_name,
            logo=logo,
            primary_color=primary_color,
            secondary_color=secondary_color,
            tertiary_color=tertiary_color,
            preference_page_url=preference_page_url,
            social_links=social_links,
            properties=properties,
            _configuration=_configuration,
            **kwargs,
        )

from supr_send_python_sdk.model.brand_create_or_update_request_social_links import BrandCreateOrUpdateRequestSocialLinks
