# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from supr_send_python_sdk import schemas  # noqa: F401


class BroadcastTriggerMessageListRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "template",
            "notification_category",
            "list_id",
        }
        
        class properties:
            list_id = schemas.StrSchema
            template = schemas.StrSchema
            notification_category = schemas.StrSchema
        
            @staticmethod
            def channels() -> typing.Type['BroadcastTriggerMessageListRequestChannels']:
                return BroadcastTriggerMessageListRequestChannels
            data = schemas.StrSchema
            delay = schemas.StrSchema
            trigger_at = schemas.DateSchema
            brand_id = schemas.StrSchema
            __annotations__ = {
                "list_id": list_id,
                "template": template,
                "notification_category": notification_category,
                "channels": channels,
                "data": data,
                "delay": delay,
                "trigger_at": trigger_at,
                "brand_id": brand_id,
            }
    
    template: MetaOapg.properties.template
    notification_category: MetaOapg.properties.notification_category
    list_id: MetaOapg.properties.list_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["list_id"]) -> MetaOapg.properties.list_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["template"]) -> MetaOapg.properties.template: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notification_category"]) -> MetaOapg.properties.notification_category: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["channels"]) -> 'BroadcastTriggerMessageListRequestChannels': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["data"]) -> MetaOapg.properties.data: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["delay"]) -> MetaOapg.properties.delay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trigger_at"]) -> MetaOapg.properties.trigger_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["brand_id"]) -> MetaOapg.properties.brand_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["list_id", "template", "notification_category", "channels", "data", "delay", "trigger_at", "brand_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["list_id"]) -> MetaOapg.properties.list_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["template"]) -> MetaOapg.properties.template: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notification_category"]) -> MetaOapg.properties.notification_category: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["channels"]) -> typing.Union['BroadcastTriggerMessageListRequestChannels', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["data"]) -> typing.Union[MetaOapg.properties.data, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["delay"]) -> typing.Union[MetaOapg.properties.delay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trigger_at"]) -> typing.Union[MetaOapg.properties.trigger_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["brand_id"]) -> typing.Union[MetaOapg.properties.brand_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["list_id", "template", "notification_category", "channels", "data", "delay", "trigger_at", "brand_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        template: typing.Union[MetaOapg.properties.template, str, ],
        notification_category: typing.Union[MetaOapg.properties.notification_category, str, ],
        list_id: typing.Union[MetaOapg.properties.list_id, str, ],
        channels: typing.Union['BroadcastTriggerMessageListRequestChannels', schemas.Unset] = schemas.unset,
        data: typing.Union[MetaOapg.properties.data, str, schemas.Unset] = schemas.unset,
        delay: typing.Union[MetaOapg.properties.delay, str, schemas.Unset] = schemas.unset,
        trigger_at: typing.Union[MetaOapg.properties.trigger_at, str, date, schemas.Unset] = schemas.unset,
        brand_id: typing.Union[MetaOapg.properties.brand_id, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BroadcastTriggerMessageListRequest':
        return super().__new__(
            cls,
            *args,
            template=template,
            notification_category=notification_category,
            list_id=list_id,
            channels=channels,
            data=data,
            delay=delay,
            trigger_at=trigger_at,
            brand_id=brand_id,
            _configuration=_configuration,
            **kwargs,
        )

from supr_send_python_sdk.model.broadcast_trigger_message_list_request_channels import BroadcastTriggerMessageListRequestChannels
