# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from supr_send_python_sdk import schemas  # noqa: F401


class TemplateGetContentChannelResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.IntSchema
        
            @staticmethod
            def channel() -> typing.Type['TemplateGetContentChannelResponseChannel']:
                return TemplateGetContentChannelResponseChannel
            is_active = schemas.BoolSchema
            is_enabled = schemas.BoolSchema
            created_at = schemas.StrSchema
            updated_at = schemas.StrSchema
        
            @staticmethod
            def disabled_languages() -> typing.Type['TemplateGetContentChannelResponseDisabledLanguages']:
                return TemplateGetContentChannelResponseDisabledLanguages
        
            @staticmethod
            def versions() -> typing.Type['TemplateGetContentChannelResponseVersions']:
                return TemplateGetContentChannelResponseVersions
            __annotations__ = {
                "id": id,
                "channel": channel,
                "is_active": is_active,
                "is_enabled": is_enabled,
                "created_at": created_at,
                "updated_at": updated_at,
                "disabled_languages": disabled_languages,
                "versions": versions,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["channel"]) -> 'TemplateGetContentChannelResponseChannel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_active"]) -> MetaOapg.properties.is_active: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_enabled"]) -> MetaOapg.properties.is_enabled: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["disabled_languages"]) -> 'TemplateGetContentChannelResponseDisabledLanguages': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["versions"]) -> 'TemplateGetContentChannelResponseVersions': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "channel", "is_active", "is_enabled", "created_at", "updated_at", "disabled_languages", "versions", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["channel"]) -> typing.Union['TemplateGetContentChannelResponseChannel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_active"]) -> typing.Union[MetaOapg.properties.is_active, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_enabled"]) -> typing.Union[MetaOapg.properties.is_enabled, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_at"]) -> typing.Union[MetaOapg.properties.updated_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["disabled_languages"]) -> typing.Union['TemplateGetContentChannelResponseDisabledLanguages', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["versions"]) -> typing.Union['TemplateGetContentChannelResponseVersions', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "channel", "is_active", "is_enabled", "created_at", "updated_at", "disabled_languages", "versions", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        channel: typing.Union['TemplateGetContentChannelResponseChannel', schemas.Unset] = schemas.unset,
        is_active: typing.Union[MetaOapg.properties.is_active, bool, schemas.Unset] = schemas.unset,
        is_enabled: typing.Union[MetaOapg.properties.is_enabled, bool, schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, str, schemas.Unset] = schemas.unset,
        updated_at: typing.Union[MetaOapg.properties.updated_at, str, schemas.Unset] = schemas.unset,
        disabled_languages: typing.Union['TemplateGetContentChannelResponseDisabledLanguages', schemas.Unset] = schemas.unset,
        versions: typing.Union['TemplateGetContentChannelResponseVersions', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TemplateGetContentChannelResponse':
        return super().__new__(
            cls,
            *args,
            id=id,
            channel=channel,
            is_active=is_active,
            is_enabled=is_enabled,
            created_at=created_at,
            updated_at=updated_at,
            disabled_languages=disabled_languages,
            versions=versions,
            _configuration=_configuration,
            **kwargs,
        )

from supr_send_python_sdk.model.template_get_content_channel_response_channel import TemplateGetContentChannelResponseChannel
from supr_send_python_sdk.model.template_get_content_channel_response_disabled_languages import TemplateGetContentChannelResponseDisabledLanguages
from supr_send_python_sdk.model.template_get_content_channel_response_versions import TemplateGetContentChannelResponseVersions
