# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from supr_send_python_sdk import schemas  # noqa: F401


class TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContent(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            text = schemas.StrSchema
            header = schemas.StrSchema
        
            @staticmethod
            def example() -> typing.Type['TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample']:
                return TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample
            vendor_slug = schemas.StrSchema
            content_type = schemas.StrSchema
            message_type = schemas.StrSchema
            template_name = schemas.StrSchema
            enterprise_name = schemas.StrSchema
            handlebars_text = schemas.StrSchema
            vendor_template_id = schemas.StrSchema
        
            @staticmethod
            def x_konfig_original_example() -> typing.Type['TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample']:
                return TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample
            __annotations__ = {
                "text": text,
                "header": header,
                "example": example,
                "vendor_slug": vendor_slug,
                "content_type": content_type,
                "message_type": message_type,
                "template_name": template_name,
                "enterprise_name": enterprise_name,
                "handlebars_text": handlebars_text,
                "vendor_template_id": vendor_template_id,
                "x-konfig-original-example": x_konfig_original_example,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["header"]) -> MetaOapg.properties.header: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["example"]) -> 'TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vendor_slug"]) -> MetaOapg.properties.vendor_slug: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["content_type"]) -> MetaOapg.properties.content_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message_type"]) -> MetaOapg.properties.message_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["template_name"]) -> MetaOapg.properties.template_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enterprise_name"]) -> MetaOapg.properties.enterprise_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["handlebars_text"]) -> MetaOapg.properties.handlebars_text: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vendor_template_id"]) -> MetaOapg.properties.vendor_template_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["x-konfig-original-example"]) -> 'TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["text", "header", "example", "vendor_slug", "content_type", "message_type", "template_name", "enterprise_name", "handlebars_text", "vendor_template_id", "x-konfig-original-example", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["text"]) -> typing.Union[MetaOapg.properties.text, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["header"]) -> typing.Union[MetaOapg.properties.header, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["example"]) -> typing.Union['TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vendor_slug"]) -> typing.Union[MetaOapg.properties.vendor_slug, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["content_type"]) -> typing.Union[MetaOapg.properties.content_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message_type"]) -> typing.Union[MetaOapg.properties.message_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["template_name"]) -> typing.Union[MetaOapg.properties.template_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enterprise_name"]) -> typing.Union[MetaOapg.properties.enterprise_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["handlebars_text"]) -> typing.Union[MetaOapg.properties.handlebars_text, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vendor_template_id"]) -> typing.Union[MetaOapg.properties.vendor_template_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["x-konfig-original-example"]) -> typing.Union['TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["text", "header", "example", "vendor_slug", "content_type", "message_type", "template_name", "enterprise_name", "handlebars_text", "vendor_template_id", "x-konfig-original-example", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        text: typing.Union[MetaOapg.properties.text, str, schemas.Unset] = schemas.unset,
        header: typing.Union[MetaOapg.properties.header, str, schemas.Unset] = schemas.unset,
        example: typing.Union['TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample', schemas.Unset] = schemas.unset,
        vendor_slug: typing.Union[MetaOapg.properties.vendor_slug, str, schemas.Unset] = schemas.unset,
        content_type: typing.Union[MetaOapg.properties.content_type, str, schemas.Unset] = schemas.unset,
        message_type: typing.Union[MetaOapg.properties.message_type, str, schemas.Unset] = schemas.unset,
        template_name: typing.Union[MetaOapg.properties.template_name, str, schemas.Unset] = schemas.unset,
        enterprise_name: typing.Union[MetaOapg.properties.enterprise_name, str, schemas.Unset] = schemas.unset,
        handlebars_text: typing.Union[MetaOapg.properties.handlebars_text, str, schemas.Unset] = schemas.unset,
        vendor_template_id: typing.Union[MetaOapg.properties.vendor_template_id, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContent':
        return super().__new__(
            cls,
            *args,
            text=text,
            header=header,
            example=example,
            vendor_slug=vendor_slug,
            content_type=content_type,
            message_type=message_type,
            template_name=template_name,
            enterprise_name=enterprise_name,
            handlebars_text=handlebars_text,
            vendor_template_id=vendor_template_id,
            _configuration=_configuration,
            **kwargs,
        )

from supr_send_python_sdk.model.template_get_details_response_channels_item_versions_item_templates_item_content_example import TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemContentExample
