# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from supr_send_python_sdk import schemas  # noqa: F401


class TemplateGetContentChannelResponseVersionsItemTemplatesItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.IntSchema
        
            @staticmethod
            def language() -> typing.Type['TemplateGetContentChannelResponseVersionsItemTemplatesItemLanguage']:
                return TemplateGetContentChannelResponseVersionsItemTemplatesItemLanguage
            is_enabled = schemas.BoolSchema
            approval_status = schemas.StrSchema
        
            @staticmethod
            def content() -> typing.Type['TemplateGetContentChannelResponseVersionsItemTemplatesItemContent']:
                return TemplateGetContentChannelResponseVersionsItemTemplatesItemContent
            created_at = schemas.StrSchema
            updated_at = schemas.StrSchema
        
            @staticmethod
            def updated_by() -> typing.Type['TemplateGetContentChannelResponseVersionsItemTemplatesItemUpdatedBy']:
                return TemplateGetContentChannelResponseVersionsItemTemplatesItemUpdatedBy
            approval_cycle = schemas.AnyTypeSchema
            is_approval_needed = schemas.BoolSchema
            is_cloned_from_last_version = schemas.BoolSchema
            __annotations__ = {
                "id": id,
                "language": language,
                "is_enabled": is_enabled,
                "approval_status": approval_status,
                "content": content,
                "created_at": created_at,
                "updated_at": updated_at,
                "updated_by": updated_by,
                "approval_cycle": approval_cycle,
                "is_approval_needed": is_approval_needed,
                "is_cloned_from_last_version": is_cloned_from_last_version,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["language"]) -> 'TemplateGetContentChannelResponseVersionsItemTemplatesItemLanguage': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_enabled"]) -> MetaOapg.properties.is_enabled: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["approval_status"]) -> MetaOapg.properties.approval_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["content"]) -> 'TemplateGetContentChannelResponseVersionsItemTemplatesItemContent': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_by"]) -> 'TemplateGetContentChannelResponseVersionsItemTemplatesItemUpdatedBy': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["approval_cycle"]) -> MetaOapg.properties.approval_cycle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_approval_needed"]) -> MetaOapg.properties.is_approval_needed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_cloned_from_last_version"]) -> MetaOapg.properties.is_cloned_from_last_version: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "language", "is_enabled", "approval_status", "content", "created_at", "updated_at", "updated_by", "approval_cycle", "is_approval_needed", "is_cloned_from_last_version", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["language"]) -> typing.Union['TemplateGetContentChannelResponseVersionsItemTemplatesItemLanguage', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_enabled"]) -> typing.Union[MetaOapg.properties.is_enabled, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["approval_status"]) -> typing.Union[MetaOapg.properties.approval_status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["content"]) -> typing.Union['TemplateGetContentChannelResponseVersionsItemTemplatesItemContent', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_at"]) -> typing.Union[MetaOapg.properties.updated_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_by"]) -> typing.Union['TemplateGetContentChannelResponseVersionsItemTemplatesItemUpdatedBy', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["approval_cycle"]) -> typing.Union[MetaOapg.properties.approval_cycle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_approval_needed"]) -> typing.Union[MetaOapg.properties.is_approval_needed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_cloned_from_last_version"]) -> typing.Union[MetaOapg.properties.is_cloned_from_last_version, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "language", "is_enabled", "approval_status", "content", "created_at", "updated_at", "updated_by", "approval_cycle", "is_approval_needed", "is_cloned_from_last_version", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        language: typing.Union['TemplateGetContentChannelResponseVersionsItemTemplatesItemLanguage', schemas.Unset] = schemas.unset,
        is_enabled: typing.Union[MetaOapg.properties.is_enabled, bool, schemas.Unset] = schemas.unset,
        approval_status: typing.Union[MetaOapg.properties.approval_status, str, schemas.Unset] = schemas.unset,
        content: typing.Union['TemplateGetContentChannelResponseVersionsItemTemplatesItemContent', schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, str, schemas.Unset] = schemas.unset,
        updated_at: typing.Union[MetaOapg.properties.updated_at, str, schemas.Unset] = schemas.unset,
        updated_by: typing.Union['TemplateGetContentChannelResponseVersionsItemTemplatesItemUpdatedBy', schemas.Unset] = schemas.unset,
        approval_cycle: typing.Union[MetaOapg.properties.approval_cycle, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        is_approval_needed: typing.Union[MetaOapg.properties.is_approval_needed, bool, schemas.Unset] = schemas.unset,
        is_cloned_from_last_version: typing.Union[MetaOapg.properties.is_cloned_from_last_version, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TemplateGetContentChannelResponseVersionsItemTemplatesItem':
        return super().__new__(
            cls,
            *args,
            id=id,
            language=language,
            is_enabled=is_enabled,
            approval_status=approval_status,
            content=content,
            created_at=created_at,
            updated_at=updated_at,
            updated_by=updated_by,
            approval_cycle=approval_cycle,
            is_approval_needed=is_approval_needed,
            is_cloned_from_last_version=is_cloned_from_last_version,
            _configuration=_configuration,
            **kwargs,
        )

from supr_send_python_sdk.model.template_get_content_channel_response_versions_item_templates_item_content import TemplateGetContentChannelResponseVersionsItemTemplatesItemContent
from supr_send_python_sdk.model.template_get_content_channel_response_versions_item_templates_item_language import TemplateGetContentChannelResponseVersionsItemTemplatesItemLanguage
from supr_send_python_sdk.model.template_get_content_channel_response_versions_item_templates_item_updated_by import TemplateGetContentChannelResponseVersionsItemTemplatesItemUpdatedBy
