# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from supr_send_python_sdk.type.broadcast_trigger_message_list_request_channels import BroadcastTriggerMessageListRequestChannels

class RequiredBroadcastTriggerMessageListRequest(TypedDict):
    # unique identifier to user list that you want to send broadcast messages to.
    list_id: str

    # Unique slug name of the template created on SuprSend dashboard. You can get this by clicking on the clipboard icon next to the Template name on SuprSend templates page.
    template: str

    # Category in which your notification belongs. You can understand more about them in the [Notification Category](https://docs.suprsend.com/docs/notification-category) documentation
    notification_category: str

class OptionalBroadcastTriggerMessageListRequest(TypedDict, total=False):
    channels: BroadcastTriggerMessageListRequestChannels

    # Mock data to replace the template variables.
    data: str

    # Broadcast will be halted for the time mentioned in delay, and become active once the delay period is over. Format - `XXdXXhXXmXXs` or if its number (n) then delay is in seconds (n)
    delay: str

    # Trigger broadcast on a specific date-time. Format - date string in ISO 8601 eg. \"2022-08-27T20:14:51.643Z\"
    trigger_at: date

    # string identifier of the brand this broadcast is associated with
    brand_id: str

class BroadcastTriggerMessageListRequest(RequiredBroadcastTriggerMessageListRequest, OptionalBroadcastTriggerMessageListRequest):
    pass
