# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from supr_send_python_sdk.type.event_trigger_event_requestuser_operations import EventTriggerEventRequestuserOperations

RequiredEventTriggerEventRequest = TypedDict("RequiredEventTriggerEventRequest", {
    # distinct_id of recipient who should receive the notification
    "distinct_id": str,

    # string identifier for the event like `product_purchased`
    "event": str,
    })

OptionalEventTriggerEventRequest = TypedDict("OptionalEventTriggerEventRequest", {
    "$user_operations": EventTriggerEventRequestuserOperations,

    # a dictionary representing event attributes like `first_name`. Event properties can be used to pass template variables in case of event based trigger
    "properties": str,

    # string identifier of the brand this event is associated with
    "brand_id": str,

    # Idempotency key (valid for 24hours)
    "$idempotency_key": str,
    }, total=False)

class EventTriggerEventRequest(RequiredEventTriggerEventRequest, OptionalEventTriggerEventRequest):
    pass
