# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemApprovalCycle(TypedDict):
    pass

class OptionalTemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemApprovalCycle(TypedDict, total=False):
    status: str

    comment: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    request_received_at: str

    sent_for_approval_at: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    approval_status_received_at: str

class TemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemApprovalCycle(RequiredTemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemApprovalCycle, OptionalTemplateGetDetailsResponseChannelsItemVersionsItemTemplatesItemApprovalCycle):
    pass
