# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from supr_send_python_sdk.type.template_get_content_channel_response_channel import TemplateGetContentChannelResponseChannel
from supr_send_python_sdk.type.template_get_content_channel_response_disabled_languages import TemplateGetContentChannelResponseDisabledLanguages
from supr_send_python_sdk.type.template_get_content_channel_response_versions import TemplateGetContentChannelResponseVersions

class RequiredTemplateGetContentChannelResponse(TypedDict):
    pass

class OptionalTemplateGetContentChannelResponse(TypedDict, total=False):
    id: int

    channel: TemplateGetContentChannelResponseChannel

    is_active: bool

    is_enabled: bool

    created_at: str

    updated_at: str

    disabled_languages: TemplateGetContentChannelResponseDisabledLanguages

    versions: TemplateGetContentChannelResponseVersions

class TemplateGetContentChannelResponse(RequiredTemplateGetContentChannelResponse, OptionalTemplateGetContentChannelResponse):
    pass
