# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from supr_send_python_sdk.type.template_get_details_response_channels_item_channel import TemplateGetDetailsResponseChannelsItemChannel
from supr_send_python_sdk.type.template_get_details_response_channels_item_disabled_languages import TemplateGetDetailsResponseChannelsItemDisabledLanguages
from supr_send_python_sdk.type.template_get_details_response_channels_item_tags import TemplateGetDetailsResponseChannelsItemTags
from supr_send_python_sdk.type.template_get_details_response_channels_item_versions import TemplateGetDetailsResponseChannelsItemVersions

class RequiredTemplateGetDetailsResponseChannelsItem(TypedDict):
    pass

class OptionalTemplateGetDetailsResponseChannelsItem(TypedDict, total=False):
    tags: TemplateGetDetailsResponseChannelsItemTags

    id: int

    channel: TemplateGetDetailsResponseChannelsItemChannel

    is_active: bool

    is_enabled: bool

    created_at: str

    updated_at: str

    disabled_languages: TemplateGetDetailsResponseChannelsItemDisabledLanguages

    versions: TemplateGetDetailsResponseChannelsItemVersions

class TemplateGetDetailsResponseChannelsItem(RequiredTemplateGetDetailsResponseChannelsItem, OptionalTemplateGetDetailsResponseChannelsItem):
    pass
