# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from supr_send_python_sdk.type.template_get_content_channel_response_versions_item_apparent_published_languages import TemplateGetContentChannelResponseVersionsItemApparentPublishedLanguages
from supr_send_python_sdk.type.template_get_content_channel_response_versions_item_published_languages import TemplateGetContentChannelResponseVersionsItemPublishedLanguages
from supr_send_python_sdk.type.template_get_content_channel_response_versions_item_templates import TemplateGetContentChannelResponseVersionsItemTemplates
from supr_send_python_sdk.type.template_get_content_channel_response_versions_item_updated_by import TemplateGetContentChannelResponseVersionsItemUpdatedBy

class RequiredTemplateGetContentChannelResponseVersionsItem(TypedDict):
    pass

class OptionalTemplateGetContentChannelResponseVersionsItem(TypedDict, total=False):
    id: int

    templates: TemplateGetContentChannelResponseVersionsItemTemplates

    status: str

    version_tag: str

    created_at: str

    updated_at: str

    updated_by: TemplateGetContentChannelResponseVersionsItemUpdatedBy

    version_tag_user: str

    published_languages: TemplateGetContentChannelResponseVersionsItemPublishedLanguages

    apparent_published_languages: TemplateGetContentChannelResponseVersionsItemApparentPublishedLanguages

class TemplateGetContentChannelResponseVersionsItem(RequiredTemplateGetContentChannelResponseVersionsItem, OptionalTemplateGetContentChannelResponseVersionsItem):
    pass
