# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from supr_send_python_sdk.type.workflow_configure_trigger_request_users_itemandroidpush import WorkflowConfigureTriggerRequestUsersItemandroidpush
from supr_send_python_sdk.type.workflow_configure_trigger_request_users_itemchannels import WorkflowConfigureTriggerRequestUsersItemchannels
from supr_send_python_sdk.type.workflow_configure_trigger_request_users_itememail import WorkflowConfigureTriggerRequestUsersItememail
from supr_send_python_sdk.type.workflow_configure_trigger_request_users_itemiospush import WorkflowConfigureTriggerRequestUsersItemiospush
from supr_send_python_sdk.type.workflow_configure_trigger_request_users_itemsms import WorkflowConfigureTriggerRequestUsersItemsms
from supr_send_python_sdk.type.workflow_configure_trigger_request_users_itemwhatsapp import WorkflowConfigureTriggerRequestUsersItemwhatsapp

RequiredWorkflowConfigureTriggerRequestUsersItem = TypedDict("RequiredWorkflowConfigureTriggerRequestUsersItem", {
    # unique identifier of the user
    "distinct_id": str,
    })

OptionalWorkflowConfigureTriggerRequestUsersItem = TypedDict("OptionalWorkflowConfigureTriggerRequestUsersItem", {
    "$channels": WorkflowConfigureTriggerRequestUsersItemchannels,

    "$email": WorkflowConfigureTriggerRequestUsersItememail,

    "$sms": WorkflowConfigureTriggerRequestUsersItemsms,

    "$whatsapp": WorkflowConfigureTriggerRequestUsersItemwhatsapp,

    "$androidpush": WorkflowConfigureTriggerRequestUsersItemandroidpush,

    "$iospush": WorkflowConfigureTriggerRequestUsersItemiospush,

    # Send Slack on a particular channel in user's profile. Use one of the methods to add slack token - 1. slack using email: {\"email\": \"user@example.com\", \"access_token\": \"xoxb-XXXXXXXX\"} ------ 2. slack using member_id: {\"user_id\": \"U/WXXXXXXXX\", \"access_token\": \"xoxb-XXXXXXXX\"} ------- 3. slack channel: {\"channel\": \"CXXXXXXXX\", \"access_token\": \"xoxb-XXXXXXXX\"} -------- 4. slack incoming webhook: {\"incoming_webhook\": { \"url\": \"https://hooks.slack.com/services/TXXXXXXXXX/BXXXXXXXX/XXXXXXXXXXXXXXXXXXX\"}}
    "$slack": str,
    }, total=False)

class WorkflowConfigureTriggerRequestUsersItem(RequiredWorkflowConfigureTriggerRequestUsersItem, OptionalWorkflowConfigureTriggerRequestUsersItem):
    pass
