# coding: utf-8

"""
    SuprSend API

    SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.

    The version of the OpenAPI document: 1.2.1
    Generated by: https://konfigthis.com
"""

from supr_send_python_sdk.paths.v1_subscriber_list.post import CreateListRaw
from supr_send_python_sdk.paths.v1_subscriber_list_list_id_delete.patch import DeleteListRaw
from supr_send_python_sdk.paths.v1_subscriber_list.get import GetAllListsRaw
from supr_send_python_sdk.paths.v1_subscriber_list_list_id.get import GetListDataRaw
from supr_send_python_sdk.paths.v1_subscriber_list_list_id_subscriber_remove.post import RemoveSubscribersFromListRaw


class SubscriberListApiRaw(
    CreateListRaw,
    DeleteListRaw,
    GetAllListsRaw,
    GetListDataRaw,
    RemoveSubscribersFromListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
